# General imports
from ast import If
import os, sys, shutil, json, re
from pydantic import BaseModel
from typing import Dict, List
from dataclasses import dataclass

# PyQt imports
from PySide6.QtCore import QObject, Signal, Qt, Slot, QThread

# Autogen imports
import autogen
from autogen import ConversableAgent, GroupChat, GroupChatManager

# UTF-8 Encoding is important for docling
sys.stdout.reconfigure(encoding='utf-8')

# TYPEDEFS
# All agent specifying information for reading in the config file
@dataclass
class agentSpecification:
    agentType: str
    name: str

# chatGraph holds all agents and their possible transitions in a concise format
# The transitions dict maps source agent names to lists of destination agent names in the exact format needed to constrain speaker transitions in autogen conversations
@dataclass
class chatGraph:
    agents: Dict[str, ConversableAgent]
    transitions: Dict[ConversableAgent, List[ConversableAgent]]



class agentChatSignals(QObject):
    outgoingMessage = Signal(dict)
    guiPopUp = Signal(str)

# Main class that allows flexible agent conversations based on config files
# Extends QObject so that it can be properly used with the GUI
class flexibleAgentChat(QObject):
    def __init__(self, configPath: str = None, llm_config = None, maxRounds: int = 10, parent = None):
        super().__init__(parent)

        # Config parsing setters
        self.configPath = configPath
        self.agentSpecs: List[agentSpecification] = []
        self.transitionSpecs: Dict[str, List[str]] = {}
        self.configIncludesTransitions = False

        # Execution-related setters
        self.llm_config = llm_config
        self.maxRounds = maxRounds
        self.interruptRequested = False

        # GUI-related setters
        self.GUI = None

        # Instantiate agents based on config in given path (if given - will not necessarily be given when instantiating through GUI).
        # This does not yet initiate the GroupChat instance or start the conversation.
        if not self.GUI and configPath:
            self.parseAgentConfig(configPath)
            self.buildAgents()

    # Register GUI and relevant signals to the agentChat class (not a signal/slot thing as registration happens while agentChat still lives on the main thread)
    # GUI cannot be type-hinted here as that would require a circular import, but it is the AgentChatGUI class from GUI.py.
    def registerGUI(self, GUI):
        # GUI import (a little unclean but makes import optional and avoids circular imports. Also there's already dynamic imports so who cares wheeeee :D)
        from flexibleAgents.GUI import AgentChatGUI

        self.GUI = GUI
        self.signals = agentChatSignals()
        self.signals.outgoingMessage.connect(self.GUI.addMessage)
        self.signals.guiPopUp.connect(self.GUI.showPopup)

    # Will be registered as a hook method to each agent, so that any message generated by an agent can be sent to the GUI for display.
    def sendMessageToGUI(self, sender: ConversableAgent, message, recipient: ConversableAgent, silent = False):
        print(f"sendMessageToGUI called with sender: {sender}, recipient: {recipient}, message: {message}, silent: {silent}")

        # Wrapping of string-only messages (as given by humanagent, for example)
        if isinstance(message, dict):
            guiMessage = message
        elif isinstance(message, str):
            print("sendMessageToGUI received string message, wrapping into dict for GUI passing.")
            guiMessage = {"name": sender.name, "content": {"message": message}}
        else:
            print(f"sendMessageToGUI received message of unsupported type {type(message)}. Message content: {message}. Defaulting to dict with only message content.")
            guiMessage = {"name": sender.name, "content": {"message": str(message)}}

        self.signals.outgoingMessage.emit(guiMessage)

        return message
    


    @Slot()
    def interruptChat(self):
        print("Interrupt requested.")
        self.interruptRequested = True



    # Parse agent chat config from text file.
    # Does not yet instantiate agents
    @Slot(str)
    def parseAgentConfig(self, path: str) -> chatGraph:
        print(f"Parsing agent config from {path}...")

        # Clear specs
        self.agentSpecs: List[agentSpecification] = []
        self.transitionSpecs: Dict[str, List[str]] = {}

        with open(path, "r") as f:
            lines = [line for line in f if line]

        # Split on first line that looks like a transition definition
        # If none exists, the transition restrictions will be lifted.
        # None sets split index to include all lines of the file --> transition-less files will be read properly
        split_index = None
        self.configIncludesTransitions = False
        for i, line in enumerate(lines):
            # Check for transition format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...
            if re.match(r'^\w+\s*:\s*\w+(,\s*\w+)*$', line.strip()):
                split_index = i
                self.configIncludesTransitions = True
                break

        # Parse agents (type and name)
        # Syntax: <agentType>, <agent_name>
        humanAgentCount = 0
        for line in lines[:split_index]:
            print(f"matching stripped line: '{line.strip()}' against agent specification regex...")
            if not re.match(r'^\w+,\s*\w+$', line.strip()):
                if self.GUI:
                    self.signals.guiPopUp.emit(f"Invalid agent specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <agentType>, <agent_name>")
                raise ValueError(f"Invalid agent specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <agentType>, <agent_name>")

            agentType, name = map(str.strip, line.split(",", 1))
            if name in [spec.name for spec in self.agentSpecs]:
                if self.GUI:
                    self.signals.guiPopUp.emit(f"Duplicate agent name found: {name}. Each agent must have a unique name. Please check the config file.")
                raise ValueError(f"Duplicate agent name found: {name}. Each agent must have a unique name. Please check the config file.")

            self.agentSpecs.append(agentSpecification(agentType, name))
            if agentType == "humanAgent":
                humanAgentCount += 1

        # Along the way, ensure a human agent is provided. Else error out.
        # A human agent is required to provide the initial query, but (by default) the queryAgent can also quit a conversation!
        if humanAgentCount != 1:
            if self.GUI:
                self.signals.guiPopUp.emit(f"Config invalid: {humanAgentCount} human agents found (exactly 1 required).")
            raise ValueError(f"Config invalid: {humanAgentCount} human agents found (exactly 1 required).")

        # Parse transitions if given
        if self.configIncludesTransitions:
            # Syntax: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...
            for line in lines[split_index:]:
                if not re.match(r'^\w+\s*:\s*\w+(,\s*\w+)*$', line.strip()):
                    if self.GUI:
                        self.signals.guiPopUp.emit(f"Invalid transition specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...")
                    raise ValueError(f"Invalid transition specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...")

                source, destinations = map(str.strip, line.split(":", 1))

                destinationList = [dest.strip() for dest in destinations.split(",") if dest.strip()]
                self.transitionSpecs[source] = destinationList

        # if self.GUI:
        #     self.signals.guiPopUp.emit("Config parsing complete.")
        print("Config parsing complete.")



    # Instantiate agents based on the parsed config
    @Slot()
    def buildAgents(self):
        print("Building agents from config...")

        if not self.agentSpecs or (self.configIncludesTransitions and not self.transitionSpecs):
            if self.GUI:
                self.signals.guiPopUp.emit("Agent specifications or transition specifications are missing. Please parse the config file first.")
            raise ValueError("Agent specifications or transition specifications are missing. Please parse the config file first.")

        # Reset chat graph (allows overriding of config at runtime)
        self.chatGraph = chatGraph(
            {},                 # Agents            Name: Agent
            {}                  # Transitions       Agent: [Agents]
        )

        # Needed for relative local imports
        sys.path.append(os.path.dirname(__file__))      
        glob = globals()
        # Dynamic Import/Instantiation of Agents
        for spec in self.agentSpecs:
            # Dynamic import of needed code
            exec(f"from agentTypes.{spec.agentType} import {spec.agentType}", glob, glob)
            # Execution of just-imported function
            agent = eval(f"{spec.agentType}(llm_config=self.llm_config, name = '{spec.name}')")

            # Register GUI message exposal to agent
            if self.GUI is not None:
                print(f"Registering hook sendMessageToGUI to {spec.name} agent")
                agent.register_hook("process_message_before_send", self.sendMessageToGUI)

            # Enter Agent into Group Chat Graph
            self.chatGraph.agents[spec.name] = agent
            # Separately keep track of the human agent for query routing
            if spec.agentType == "humanAgent":          
                self.humanAgent = agent
            

        # Build transitions dict in required format for autogen conversations (converts keys and values from names to agent instances)
        for source_name, dest_names in self.transitionSpecs.items():
            source_agent = self.chatGraph.agents[source_name]
            dest_agents = [self.chatGraph.agents[dest_name] for dest_name in dest_names]
            self.chatGraph.transitions[source_agent] = dest_agents

        print("Agent building complete.")

        return

    def checkTermination(self, message) -> bool:
        # print(f"Checking for termination signal in message {message}...")

        # Check if the message contains a termination signal (this is a very basic implementation and can be expanded based on how exactly the termination signal is structured)
        if self.interruptRequested:
            print("Termination requested by GUI interrupt.")
            return True
        
        # Check for terrmination signal in message content (looking for a field "terminateChat" set to True within JSON content string)
        if isinstance(message, dict):
            # Load JSON string into dict if content is valid JSON string.
            try:
                content = json.loads(message["content"])
                # Check for termination signal (False if field is nonexistent)
                termination = content.get("terminateChat", False)
                if termination == True:
                    print("Termination signal received from agent message content.")
                    if self.GUI:
                        self.signals.outgoingMessage.emit({"name": "System", "content": {"message": "Termination signal received. Ending conversation..."}})
                    return True
                else:
                    print("No termination signal in agent message content.")
                    return False
            # If not, nothing happens.
            except json.JSONDecodeError:
                print("Not JSON content, no termination signal.")
                return False
        else:
            return False

    # Start the group chat using the pattern created from config file, adding in the agent chat config for evaluation
    @Slot(str)
    def startConversation(self, query: str):
        print(f"Starting conversation with query: {query}")

        if self.GUI:
            self.signals.outgoingMessage.emit({"name": "System", "content": {"message": f"Starting conversation with query: {query}"}})

        # If no transitions were given, we can simply switch the GroupChat to allow all transitions by switching them from allowed to disallowed
        if self.configIncludesTransitions:
            transitionType = "allowed"
        else:
            transitionType = "disallowed"

        # Initialize a group chat with the instantiated agents and the query
        agentList = list(self.chatGraph.agents.values())
        groupchat = GroupChat(
            agents=agentList,
            messages=[],
            send_introductions=True,
            max_round=self.maxRounds,
            allowed_or_disallowed_speaker_transitions=self.chatGraph.transitions,
            speaker_transitions_type=transitionType,
            speaker_selection_method="auto"
        )

        # Process flow within this group chat is managed by the following manager (necessary even when agents are choosing their own transitions, then it will simply not use an llm but the fixed rules)
        # Termination condition: if interrupt requested by GUI or if agent signals termination through its output (default: only doable by queryAgent)
        manager = GroupChatManager(
            groupchat=groupchat,
            llm_config=self.llm_config,
            name = "ManagerAgent",
            is_termination_msg = self.checkTermination
        )

        # Clear and re-initialize conversation history directory (deletion and recreation of directory, no undoing this!) before chat starts
        shutil.rmtree(f"{os.path.dirname(__file__)}/tempConversation", ignore_errors=True)
        os.makedirs(f"{os.path.dirname(__file__)}/tempConversation/data", exist_ok=True)
        os.makedirs(f"{os.path.dirname(__file__)}/tempConversation/tempDownloads", exist_ok=True)

        # Clear interruption request state at the beginning of the conversation
        self.interruptRequested = False

        # Start the conversation with the prompt coming from the human and being passed to the manager.
        # We have to pass to the manager to make the GroupChat work properly - else we will just get replies from the one agent.
        # TODO figure out how exactly to expose the messages as they are generated (probably a hook method?) and expose them to the GUI
        result = self.humanAgent.initiate_chat(
            manager,
            message=query,
            clear_history=False
        )

        print("Conversation finished.")

        print("Saving conversation history...")

        # Save conversation history as text file in temp directory
        # Wanted to simplify to make this a simple loadable json but kinda can't get it to work as json loads keeps failing
        path = os.path.join(os.path.dirname(__file__), "tempConversation", "conversation.txt")
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"Conversation Log for query: {query}\n\n")
            for msg in groupchat.messages:
                name = msg.get("name", "unknown")
                content = msg.get("content", "")

                # Try to pretty-print JSON content when possible, otherwise write raw content
                formatted = None
                if isinstance(content, (dict, list)):
                    formatted = json.dumps(content, indent=4)
                else:
                    try:
                        parsed = json.loads(content)
                        formatted = json.dumps(parsed, indent=4)
                    except Exception:
                        formatted = str(content)

                # Write to file and also print so manager/summary messages are visible in the terminal
                f.write(f"{name}:\n{formatted}\n\n")

        print("Conversation history saved.")

        # Return all messages for potential further processing
        return
    
