# General imports
from ast import If
import os, sys, shutil, json, re, random, string
from pydantic import BaseModel
from typing import Dict, List
from dataclasses import dataclass

# PyQt imports
print("Importing PyQt6...")
from PySide6.QtCore import QObject, Signal, Qt, Slot, QThread

# Autogen imports
print("Importing ConversableAgent...")
from autogen import ConversableAgent
print("Importing GroupChat...")
from autogen import GroupChat
print("Importing GroupChatManager...")
from autogen import GroupChatManager
print("Importing gather_usage_summary...")
from autogen import gather_usage_summary
print("Done")

# UTF-8 Encoding
sys.stdout.reconfigure(encoding='utf-8')

# TYPEDEFS
# All agent specifying information for reading in the config file
@dataclass
class agentSpecification:
	agentType: str
	name: str

# chatGraph holds all agents and their possible transitions in a concise format
# The transitions dict maps source agent names to lists of destination agent names in the exact format needed to constrain speaker transitions in autogen conversations
@dataclass
class chatGraph:
	agents: Dict[str, ConversableAgent]
	transitions: Dict[ConversableAgent, List[ConversableAgent]]

class agentChatSignals(QObject):
	outgoingMessage = Signal(dict)
	guiPopUp = Signal(str)

# Main class that allows flexible agent conversations based on config files
# Extends QObject so that it can be properly used with the GUI
class flexibleAgentChat(QObject):
	def __init__(self, configPath: str = None, llm_config = None, conversationPath = None, maxRounds: int = 10, trackTokens: bool = False, resetAfterConversation: bool = False, parent = None):
		super().__init__(parent)

		# Config parsing setters
		self.configPath = configPath
		self.agentSpecs: List[agentSpecification] = []
		self.transitionSpecs: Dict[str, List[str]] = {}
		self.configIncludesTransitions = False
		self.noHumanInput = False

		# Execution-related setters
		self.llm_config = llm_config
		self.maxRounds = maxRounds
		self.interruptRequested = False
		self.resetAfterConversation = resetAfterConversation

		# Conversation path
		# If none is given, create a new temporary conversation directory with a random string to avoid overwriting previous conversations.
		# If given, use the provided path.
		self.isConversationPathRandom = False
		if conversationPath:
			self.conversationPath = conversationPath
		else:
			randomString = "".join(random.choices(string.ascii_letters, k=10))
			conversationsDir = os.path.join(os.path.dirname(__file__), "tempConversation")
			# Ensure random directory name doesn't exist yet (incredibly unlikely, safeguard still sensible to have)
			while os.path.exists(os.path.join(conversationsDir, f"conversation_{randomString}")):
				print("Collision in random conversation directory name, generating a new one...")
				randomString = "".join(random.choices(string.ascii_letters, k=10))
			self.conversationPath = os.path.join(conversationsDir, f"conversation_{randomString}")
			self.isConversationPathRandom = True

		print(f"Conversation path set to {self.conversationPath}. Creating directory if it doesn't exist...")
		os.makedirs(self.conversationPath, exist_ok=True)

		# GUI-related setters
		self.GUI = None

		# Output related setters
		self.trackTokens = trackTokens

		# Instantiate agents based on config in given path (if given - will not necessarily be given when instantiating through GUI).
		# This does not yet initiate the GroupChat instance or start the conversation.
		if not self.GUI and configPath:
			self.parseAgentConfig(configPath)
			self.buildAgents()

	# Register GUI and relevant signals to the agentChat class (not a signal/slot thing as registration happens while agentChat still lives on the main thread)
	# GUI cannot be type-hinted here as that would require a circular import, but it is the AgentChatGUI class from GUI.py.
	def registerGUI(self, GUI):
		# GUI import (a little unclean but makes import optional and avoids circular imports. Also there's already dynamic imports so who cares wheeeee :D)
		from flexibleAgents.GUI import AgentChatGUI

		self.GUI = GUI
		self.signals = agentChatSignals()
		self.signals.outgoingMessage.connect(self.GUI.addMessage)
		self.signals.guiPopUp.connect(self.GUI.showPopup)

	# Will be registered as a hook method to each agent, so that any message generated by an agent can be sent to the GUI for display.
	def sendMessageToGUI(self, sender: ConversableAgent, message, recipient: ConversableAgent, silent = False):
		print(f"sendMessageToGUI called with sender: {sender}, recipient: {recipient}, message: {message}, silent: {silent}")

		# Wrapping of string-only messages (as given by humanagent, for example)
		if isinstance(message, dict):
			guiMessage = message
		elif isinstance(message, str):
			print("sendMessageToGUI received string message, wrapping into dict for GUI passing.")
			guiMessage = {"name": sender.name, "content": {"message": message}}
		else:
			print(f"sendMessageToGUI received message of unsupported type {type(message)}. Message content: {message}. Defaulting to dict with only message content.")
			guiMessage = {"name": sender.name, "content": {"message": str(message)}}

		self.signals.outgoingMessage.emit(guiMessage)

		return message
	
	@Slot()
	def interruptChat(self):
		print("Interrupt requested.")
		self.interruptRequested = True

	# Parse agent chat config from text file.
	# Does not yet instantiate agents
	@Slot(str)
	def parseAgentConfig(self, path: str) -> chatGraph:
		print(f"Parsing agent config from {path}...")

		# Clear specs
		self.agentSpecs: List[agentSpecification] = []
		self.transitionSpecs: Dict[str, List[str]] = {}

		with open(path, "r") as f:
			lines = [line for line in f if line != "\n"]  # Remove empty lines

		# Split on first line that looks like a transition definition
		# If none exists, the transition restrictions will be lifted.
		# None sets split index to include all lines of the file --> transition-less files will be read properly
		end_of_spec_index = None
		start_of_transitions_index = None
		self.configIncludesTransitions = False
		for i, line in enumerate(lines):
			# Check for transition format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...
			if re.match(r'^\w+\s*:\s*\w+(,\s*\w+)*$', line.strip()):
				if end_of_spec_index == None:
					end_of_spec_index = i
				start_of_transitions_index = i
				self.configIncludesTransitions = True
				break
			elif line.strip() == "noHumanInput":
				end_of_spec_index = i
				self.noHumanInput = True

		# Parse agents (type and name)
		# Syntax: <agentType>, <agent_name>
		humanAgentCount = 0
		for line in lines[:end_of_spec_index]:
			print(f"matching stripped line: '{line.strip()}' against agent specification regex...")
			if not re.match(r'^\w+,\s*\w+$', line.strip()):
				if self.GUI:
					self.signals.guiPopUp.emit(f"Invalid agent specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <agentType>, <agent_name>")
				raise ValueError(f"Invalid agent specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <agentType>, <agent_name>")

			agentType, name = map(str.strip, line.split(",", 1))
			if name in [spec.name for spec in self.agentSpecs]:
				if self.GUI:
					self.signals.guiPopUp.emit(f"Duplicate agent name found: {name}. Each agent must have a unique name. Please check the config file.")
				raise ValueError(f"Duplicate agent name found: {name}. Each agent must have a unique name. Please check the config file.")

			self.agentSpecs.append(agentSpecification(agentType, name))
			if agentType == "humanAgent":
				humanAgentCount += 1
				self.humanAgentName = name

		# Along the way, ensure a human agent is provided. Else error out.
		# A human agent is required to provide the initial query, but (by default) the queryAgent can also quit a conversation!
		if humanAgentCount != 1:
			if self.GUI:
				self.signals.guiPopUp.emit(f"Config invalid: {humanAgentCount} human agents found (exactly 1 required).")
			raise ValueError(f"Config invalid: {humanAgentCount} human agents found (exactly 1 required).")

		# Default to allowing all unspecified transitions except for self-transitions
		fullDestinationList = [spec.name for spec in self.agentSpecs]
		for source in self.agentSpecs:
			self.transitionSpecs[source.name] = fullDestinationList.copy()
			self.transitionSpecs[source.name].remove(source.name)

		# Parse transitions if given, removing transition options
		if self.configIncludesTransitions:
			# Syntax: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...
			for line in lines[start_of_transitions_index:]:
				if not re.match(r'^\w+\s*:\s*\w+(,\s*\w+)*$', line.strip()):
					if self.GUI:
						self.signals.guiPopUp.emit(f"Invalid transition specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...")
					raise ValueError(f"Invalid transition specification: {line}.\nStripped to: {line.strip()}.\nExpected format: <source_agent_name>: <destination_agent_name>, <destination_agent_name>, ...")

				source, destinations = map(str.strip, line.split(":", 1))

				destinationList = [dest.strip() for dest in destinations.split(",") if dest.strip()]
				self.transitionSpecs[source] = destinationList

		# Explicitly remove transitions going to to human agent if noHumanInput is set
		if self.noHumanInput:
			for source in self.transitionSpecs:
				if self.humanAgentName in self.transitionSpecs[source]:
					self.transitionSpecs[source].remove(self.humanAgentName)

		print("Config parsing complete.")

		return

	# Instantiate agents based on the parsed config
	@Slot()
	def buildAgents(self):
		print("Building agents from config...")

		if not self.agentSpecs or (self.configIncludesTransitions and not self.transitionSpecs):
			if self.GUI:
				self.signals.guiPopUp.emit("Agent specifications or transition specifications are missing. Please parse the config file first.")
			raise ValueError("Agent specifications or transition specifications are missing. Please parse the config file first.")

		# Reset chat graph (allows overriding of config at runtime)
		self.chatGraph = chatGraph(
			{},				 # Agents			Name: Agent
			{}				  # Transitions	   Agent: [Agents]
		)

		# Needed for relative local imports
		sys.path.append(os.path.dirname(__file__))	  
		glob = globals()
		# Dynamic Import/Instantiation of Agents
		for spec in self.agentSpecs:
			print(f"Importing and instantiating agent {spec.name} of type {spec.agentType}...")
			# Dynamic import of needed code
			exec(f"from agentTypes.{spec.agentType} import {spec.agentType}", glob, glob)
			# Execution of just-imported function
			agent = eval(f"{spec.agentType}(chat = self, name = '{spec.name}')")

			# Register GUI message exposal to agent
			if self.GUI is not None:
				print(f"Registering hook sendMessageToGUI to {spec.name} agent")
				agent.register_hook("process_message_before_send", self.sendMessageToGUI)

			# Enter Agent into Group Chat Graph
			self.chatGraph.agents[spec.name] = agent
			# Separately keep track of the human agent for query routing
			if spec.agentType == "humanAgent":
				self.humanAgent = agent
			
		# Build transitions dict in required format for autogen conversations (converts keys and values from names to agent instances)
		print(self.transitionSpecs)
		for source_name, dest_names in self.transitionSpecs.items():
			source_agent = self.chatGraph.agents[source_name]
			dest_agents = [self.chatGraph.agents[dest_name] for dest_name in dest_names]
			self.chatGraph.transitions[source_agent] = dest_agents

		print("Agent building complete. Compiling into GroupChat...")

		self.initGroupChatAndManager()

		print("GroupChat initialization complete.")

		return
	

	def initGroupChatAndManager(self):
		# Initialize a group chat with the instantiated agents and the query
		agentList = list(self.chatGraph.agents.values())
		self.groupchat = GroupChat(
			agents=agentList,
			messages=[],
			send_introductions=True,
			max_round=self.maxRounds,
			allowed_or_disallowed_speaker_transitions=self.chatGraph.transitions,
			speaker_transitions_type="allowed",
			speaker_selection_method="auto"
		)

		# Process flow within this group chat is managed by the following manager (necessary even when agents are choosing their own transitions, then it will simply not use an llm but the fixed rules)
		# Termination condition: if interrupt requested by GUI or if agent signals termination through its output (default: only doable by queryAgent)
		self.manager = GroupChatManager(
			groupchat=self.groupchat,
			llm_config=self.llm_config,
			name = "ManagerAgent",
			is_termination_msg = self.checkTermination
		)

	# Return path to conversation history
	def getConversationPath(self):
		return self.conversationPath
	
	# Set path to conversation history (useful for testing, where this changes between each test)
	def setConversationPath(self, path):
		# Check if old, temporary dir was empty - if yes, clear it out. If not, leave it be to avoid accidental deletion of conversation histories.
		if os.path.exists(self.conversationPath) and len(os.listdir(self.conversationPath)) == 0 and self.isConversationPathRandom:
			shutil.rmtree(self.conversationPath, ignore_errors=True)
		
		self.conversationPath = path
		self.isConversationPathRandom = False

		# Set up path for conversation history text file within the new conversation directory
		self.setupConversationHistoryPath()
		
		return

	def checkTermination(self, message) -> bool:
		# Add message to history text file
		self.saveLastMessageToConversationHistory(message)

		# Check if the message contains a termination signal (this is a very basic implementation and can be expanded based on how exactly the termination signal is structured)
		if self.interruptRequested:
			print("Termination requested by GUI interrupt.")
			return True
		
		# Check for terrmination signal in message content (looking for a field "terminateChat" set to True within JSON content string)
		if isinstance(message, dict):
			# Load JSON string into dict if content is valid JSON string.
			try:
				content = json.loads(message["content"])
				# Check for termination signal (False if field is nonexistent)
				termination = content.get("terminateChat", False)
				if termination == True and self.noHumanInput:
					print("Termination signal received from agent message content in noHumanInput mode.")
					if self.GUI:
						self.signals.outgoingMessage.emit({"name": "System", "content": {"message": "Termination signal received. Ending conversation..."}})
					return True
				else:
					# print("No termination signal in agent message content.")
					return False
			# If not, nothing happens.
			except json.JSONDecodeError:
				# print("Not JSON content, no termination signal.")
				return False
		else:
			return False

	def setupConversationHistoryPath(self):
		# Find non-duplicate conversation name for text file
		counter = 1
		while True:
			filename = f"conversation_{counter}.txt"
			if not os.path.exists(os.path.join(self.conversationPath, filename)):
				break
			counter += 1

		self.conversationHistoryPath = os.path.join(self.conversationPath, filename)

	def initializeConversationHistory(self, query: str = None):
		# Ensure conversation history file exists and is empty at the start of the conversation
		with open(self.conversationHistoryPath, "w", encoding="utf-8") as f:
			f.write(f"Conversation Log for query: {query}\n\n")

	# Save last msg in conversation history into text file
	def saveLastMessageToConversationHistory(self, msg):
		# Append last msg in conversation history to text file
		with open(self.conversationHistoryPath, "a", encoding="utf-8") as f:
			name = msg.get("name", "unknown")
			content = msg.get("content", "")

			# Try to pretty-print JSON content when possible, otherwise write raw content
			formatted = None
			if isinstance(content, (dict, list)):
				formatted = json.dumps(content, indent=4)
			else:
				try:
					parsed = json.loads(content)
					formatted = json.dumps(parsed, indent=4).replace("\\n", "\n")
				except Exception:
					formatted = str(content)

			# Write to file and also print so manager/summary messages are visible in the terminal
			f.write(f"{name}:\n{formatted}\n\n")



	# Start the group chat using the pattern created from config file, adding in the agent chat config for evaluation
	@Slot(str)
	def startConversation(self, query: str):
		# print(f"Starting conversation with query: {query}")

		if self.GUI:
			self.signals.outgoingMessage.emit({"name": "System", "content": {"message": f"Starting conversation with query: {query}"}})

		# Clear interruption request state at the beginning of the conversation
		self.interruptRequested = False

		# Init convo history file
		self.setupConversationHistoryPath()
		self.initializeConversationHistory(query)

		# Start the conversation with the prompt coming from the human and being passed to the manager.
		# We have to pass to the manager to make the GroupChat work properly - else we will just get replies from the one agent.
		# I'm unsure if clearing the history here equates to a full agent reset, so I've opted to do it separately if required.
		result = self.humanAgent.initiate_chat(
			self.manager,
			message=query,
			clear_history=False
		)

		# Return all messages for potential further processing, including agent usage summary if asked
		# Calculate total tokens used if tracking enabled
		if self.trackTokens:
			tokenUsage = gather_usage_summary(self.groupchat.agents + [self.manager])
			messageHistory = self.groupchat.messages.copy()

			print(f"Cost including cached inference: {tokenUsage['usage_including_cached_inference']['total_cost']}")
			print(f"Cost excluding cached inference: {tokenUsage['usage_excluding_cached_inference']['total_cost']}")

			# Reset token usage for re-use of FlexibleAgents instance
			if self.resetAfterConversation:
				for agent in self.groupchat.agents + [self.manager]:
					agent.reset()

			return messageHistory, tokenUsage
		else:
			if self.resetAfterConversation:
				for agent in self.groupchat.agents + [self.manager]:
					agent.reset()
			
			return self.groupchat.messages
	
