from typing import Dict, List
from autogen import ConversableAgent
from pydantic import BaseModel

# Define code critic agent response format
class codeCriticAgentResponse(BaseModel):
	message: str					# Message to the user about the code critique, especially focusing on logical consistency, and potential improvements

# Query Agent takes in the initial query and then delegates tasks to other agents
# Based on the user's input, it breaks down the task into sub-tasks for other agents to handle
# Each Conversation Config must include a Query Agent as the starting point
def codeCriticAgent(chat, name = "CodeCriticAgent") -> ConversableAgent:
	systemMessage = f"""
		You are a CODE CRITIC Agent specializing in evaluating the logical consistency, security, and potential improvements of code snippets generated by other agents in the system.
		You will analyze the code snippets provided by other agents in the system.
        Based on the task, you should provide a thorough code critique.
		
		Your output includes a message field:
        - The message field should include a rundown of your code critique. If specific improvements can be made, include them in a clear and concise manner. Focus on logical consistency, potential bugs, security vulnerabilities, and overall code quality.
	"""

	description = """
		The CODE CRITIC AGENT is responsible for evaluating and providing feedback on code snippets generated by other agents in the system.
		It ensures that the code meets the required standards and provides constructive feedback for enhancements.
		The Code Critic should only be called after a code-generated agent.
	"""

	codeCritic_llm_config = chat.llm_config.copy()
	codeCritic_llm_config["response_format"] = codeCriticAgentResponse

	return ConversableAgent(
		name = name,
		system_message = systemMessage,
		description = description,
		llm_config = codeCritic_llm_config,
		human_input_mode="NEVER"
	)
